# config.yaml
device: cpu
n_classes: 206
classifier_dropout: 0.5
top_db: 80

# spectrogram parameters
spec_params:
  sample_rate: 16000
  n_mels: 128
  f_min: 20
  f_max: 15000
  n_fft: 2048
  hop_length: 256
  normalized: true

normalize_config:
  normalize_standart: true
  normalize_minmax: true

# backbone
backbone: tf_efficientnet_b0.in1k
pretrained: true
pool_type: adavg
out_indices: [2, 3]
in_chans: 3
timm_kwargs: null
